### ISSUE TITLE
Handle modinfo files for macOS app bundles

### ISSUE THREAD

**Issue by scheibel** [cginternals/cpplocate#3]
Extend the modinfo generation, management and installation scripts to handle macOS app bundles correctly. Thereby, the scripts should detect the usage with macOS app bundles by checking the ```MACOSX_BUNDLE``` property of the target.

**Comment by scheibel** [comment]
I think this is added by now?

**Comment by sbusch42** [comment]
No, it isn't. We have switched to a modinfo-free variant, but anyone using the modinfo files will still have the same issues with app bundles. It would be easy to fix, though: Extend findModule() to first look at the executable path, then at the bundle path. Only if both fails, go on to searching the system.

**Comment by scheibel** [comment]
We dropped modinfo files, so this issue is now obsolete.
