### ISSUE TITLE
Support multiple lib extensions

### ISSUE THREAD

**Issue by j-o** [cginternals/cpplocate#39]
Currently, `libExtension` returns a single value; however, there are three commonly used extension for libraries on macOS: `dylib`, `so`, and `bundle` (see https://stackoverflow.com/a/2339910). This is also partially the case in CMake: `add_library(mytarget SHARED)` generates a `.dylib` file, while `add_library(mytarget MODULE)` (which is actually the correct type for dynamically loaded plugins) generates a `.so` file.

**Comment by sbusch42** [comment]
This method returns the shared library extension, as the documentation states: "Get platform specific shared library extension". This is needed e.g. to locate plugin libraries at runtime. At the moment, I see no reason to get any of the other library extension at runtime. Do you see any use case for that?

**Comment by j-o** [comment]
Exactly. `bundle` would be considered a plugin, too, although it is more than just a shared library, so this one may be out of scope here.
