### ISSUE TITLE
Test fails with unset `DISPLAY` environment variable Linux

### ISSUE THREAD

**Issue by ekilmer** [cginternals/cpplocate#44]
Hello, thank you for the project!

I was trying to run the tests and ran into an issue with my environment not setting the `DISPLAY` environment variable when I was SSH'ed into my Linux box, which caused a test failure.

```
...
[==========] 41 tests from 2 test suites ran. (1 ms total)
[  PASSED  ] 40 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] utils_test.getEnv_Value
```

After looking at [the test](https://github.com/cginternals/cpplocate/blob/2ad2bfc17f17272dc2c4dd552bb24001e97a31dc/source/tests/liblocate-test/utils_test.cpp#L233-L247), would it be better to set a dummy environment variable using a standard library function and then read it back to test the value? Possibly like the following?

```diff
diff --git a/source/tests/liblocate-test/utils_test.cpp b/source/tests/liblocate-test/utils_test.cpp
index 0395652..67f508a 100644
--- a/source/tests/liblocate-test/utils_test.cpp
+++ b/source/tests/liblocate-test/utils_test.cpp
@@ -1,3 +1,4 @@
+#include <cstdlib>

 #include <gmock/gmock.h>

@@ -230,12 +231,14 @@ TEST_F(utils_test, getEnv_Value)

     free(value);
 #else
-    const char * key = "DISPLAY";
+    const char * key = "CPPLOCATE_DISPLAY";
     const unsigned int keyLength = strlen(key);

     char * value = nullptr;
     unsigned int valueLength = 0;

+    setenv(key, ":0", true);
+
     getEnv(key, keyLength, &value, &valueLength);

     // Display is in format ':[display number]'
```

**Comment by scheibel** [comment]
Thanks for reporting. I've integrated your patch.
