### ISSUE TITLE
Add FetchContent to build instructions

### ISSUE THREAD

**Issue by ryouze** [cginternals/cpplocate#50]
[FetchContent](https://www.foonathan.net/2022/06/cmake-fetchcontent/) is a built-in CMake module (v3.11 or above) that allows the user to download a library at configure time. It is very convenient and available for many well-known libraries, such as [json](https://github.com/nlohmann/json?tab=readme-ov-file#embedded-fetchcontent) and [SFML](https://github.com/SFML/cmake-sfml-project).

I have tested it with your library and it works out of the box. Therefore, I'd suggest adding instructions for FetchContent to the Build Instructions section in `README.md`.

I'd suggest something similar to this:

---

##### Compile Instructions

For compilation, a C++11 compliant compiler, e.g., GCC 4.8, Clang 3.3, MSVC 2013 **Update 3**, is required.

You can use FetchContent (CMake v3.11 or above) to download the library at configure time by adding the following to your `CMakeLists.txt`:

```cmake
include(FetchContent)

FetchContent_Declare(cpplocate
  URL https://github.com/cginternals/cpplocate/archive/refs/tags/v2.3.0.zip  # Choose the desired version from Releases
)
FetchContent_MakeAvailable(cpplocate)

target_link_libraries(${target} ... PUBLIC cpplocate::cpplocate)
```

Alternatively, download the source code [as archive](https://github.com/cginternals/cpplocate/releases) or via git:

_The old the instructions go here..._

**Comment by sbusch42** [comment]
As you may have concluded already, this library is not actively maintained any more. I don't have any time left to actively work on it, neither have any of the other former contributors. Therefore, we are also not following the development of CMake any more, so we have missed a lot of development there, I'm sure.

If you are willing to open a PR with the changes to the documentation your are suggesting, I'm happy to merge it, though.
